version: '3.9'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    ports:
      - "3307:3306"
    env_file:
      - ./.env/db/.env
    volumes:
      - ./.env/db/data:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8089:8089"